/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "proto/comms_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(comms_protocol_CommsMessage, comms_protocol_CommsMessage, AUTO)


PB_BIND(comms_protocol_Status, comms_protocol_Status, AUTO)


PB_BIND(comms_protocol_Command, comms_protocol_Command, AUTO)


PB_BIND(comms_protocol_Response, comms_protocol_Response, AUTO)













