# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comms_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omms_protocol.proto\x12\x0e\x63omms_protocol\"\x85\x02\n\x0c\x43ommsMessage\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.comms_protocol.MessageType\x12&\n\x06\x64\x65vice\x18\x03 \x01(\x0e\x32\x16.comms_protocol.Device\x12*\n\x07\x63ommand\x18\x04 \x01(\x0b\x32\x17.comms_protocol.CommandH\x00\x12,\n\x08response\x18\x05 \x01(\x0b\x32\x18.comms_protocol.ResponseH\x00\x12(\n\x06status\x18\x06 \x01(\x0b\x32\x16.comms_protocol.StatusH\x00\x42\x05\n\x03msg\"C\n\x06Status\x12*\n\x05state\x18\x02 \x01(\x0e\x32\x1b.comms_protocol.DeviceState\x12\r\n\x05ticks\x18\x03 \x01(\r\"a\n\x07\x43ommand\x12\x31\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x1b.comms_protocol.CommandType\x12\x18\n\x0e\x64\x65\x66\x61ultpayload\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"P\n\x08Response\x12\x33\n\rresponse_code\x18\x01 \x01(\x0e\x32\x1c.comms_protocol.ResponseCode\x12\x0f\n\x07payload\x18\x02 \x01(\x0c*\x1c\n\x06\x44\x65vice\x12\x07\n\x03RPI\x10\x00\x12\t\n\x05STM32\x10\x01*A\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\n\n\x06STATUS\x10\x03*\'\n\x0b\x43ommandType\x12\r\n\tFLIP_PAGE\x10\x00\x12\t\n\x05RESET\x10\x01*1\n\x0b\x44\x65viceState\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0b\n\x07STOPPED\x10\x02*H\n\x0cResponseCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x13\n\x0fINVALID_COMMAND\x10\x02\x12\x0b\n\x07TIMEOUT\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comms_protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICE._serialized_start=554
  _DEVICE._serialized_end=582
  _MESSAGETYPE._serialized_start=584
  _MESSAGETYPE._serialized_end=649
  _COMMANDTYPE._serialized_start=651
  _COMMANDTYPE._serialized_end=690
  _DEVICESTATE._serialized_start=692
  _DEVICESTATE._serialized_end=741
  _RESPONSECODE._serialized_start=743
  _RESPONSECODE._serialized_end=815
  _COMMSMESSAGE._serialized_start=41
  _COMMSMESSAGE._serialized_end=302
  _STATUS._serialized_start=304
  _STATUS._serialized_end=371
  _COMMAND._serialized_start=373
  _COMMAND._serialized_end=470
  _RESPONSE._serialized_start=472
  _RESPONSE._serialized_end=552
# @@protoc_insertion_point(module_scope)
